(in-package :cl)
(defpackage :openrdf.vocabulary (:use :cl :openrdf.model)
            (:export :+ns+
                     :+duration+
                     :+datetime+
                     :time+
                     :+date+
                     :+gyearmonth+
                     :+gyear+
                     :+gmonthday+
                     :+gday+
                     :+gmonth+
                     :+string+
                     :+boolean+
                     :+base64binary+
                     :+hexbinary+
                     :+float+
                     :+decimal+
                     :+double+
                     :+anyuri+
                     :+qname+
                     :+notation+
                     :+normalizedstring+
                     :+token+
                     :+language+
                     :+nmtoken+
                     :+nmtokens+
                     :+name+
                     :+ncname+
                     :+id+
                     :+idref+
                     :+idrefs+
                     :+entity+
                     :+entities+
                     :+integer+
                     :+long+
                     :+int+
                     :+short+
                     :+number+
                     :+byte+
                     :+non-positive-integer+
                     :+negative-nteger+
                     :+non-negative-integer+
                     :+positive-nteger+
                     :+unsigned-long+
                     :+unsigned-int+
                     :+unsigned-short+
                     :+unsigned-byte+))
